-include device/lemfo/LEM5PRO/device.mk

PRODUCT_BUILD_PROP_OVERRIDES += BUILD_UTC_DATE=0
PRODUCT_NAME := full_LEM5PRO
PRODUCT_DEVICE := LEM5PRO

PRODUCT_DEFAULT_LANGUAGE := hu
PRODUCT_DEFAULT_REGION   := HU